name: 'Setup iOS Build Environment'
description: 'Complete setup for iOS CI/CD jobs including Xcode, tools, Ruby, and config files'
inputs:
  xcode-version:
    description: 'Xcode version to use'
    required: false
    default: '16.1'
  install-tools:
    description: 'Install SwiftLint and xcbeautify'
    required: false
    default: 'true'
  setup-ruby:
    description: 'Setup Ruby and Bundler'
    required: false
    default: 'true'
  create-config-files:
    description: 'Create placeholder config files'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}
    
    - name: Install Homebrew dependencies
      if: inputs.install-tools == 'true'
      shell: bash
      run: |
        cd apps/ios
        export PATH="/opt/homebrew/bin:$PATH"
        echo "Installing Homebrew dependencies with bundle..."
        brew bundle --no-upgrade
    
    - name: Cache Ruby dependencies
      if: inputs.setup-ruby == 'true'
      uses: actions/cache@v4
      with:
        path: apps/ios/vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    
    - name: Setup Ruby and Bundler
      if: inputs.setup-ruby == 'true'
      shell: bash
      run: |
        cd apps/ios
        gem install bundler:2.4.10
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    
    - name: Create placeholder config files
      if: inputs.create-config-files == 'true'
      shell: bash
      run: |
        cd apps/ios
        
        # Create Supabase config
        echo "// CI Placeholder" > Supabase.xcconfig
        echo "SUPABASE_URL = https://placeholder.supabase.co" >> Supabase.xcconfig
        echo "SUPABASE_ANON_KEY = placeholder-key" >> Supabase.xcconfig
        
        # Create LogYourBody config
        echo "// CI Placeholder" > LogYourBody/Config.xcconfig
        echo "CLERK_PUBLISHABLE_KEY = placeholder-clerk-key" >> LogYourBody/Config.xcconfig