#!/bin/bash

echo "🧪 Testing Supabase Connection and Setup"
echo "========================================"
echo ""
echo "Your Supabase project: ihivupqpctpkrgqgxfjf"
echo ""
echo "📋 Quick Setup Steps:"
echo ""
echo "1. Go to SQL Editor:"
echo "   https://supabase.com/dashboard/project/ihivupqpctpkrgqgxfjf/sql"
echo ""
echo "2. Copy the entire contents of: supabase/setup-auth.sql"
echo ""
echo "3. Paste and run in SQL Editor"
echo ""
echo "4. Configure email templates (optional):"
echo "   https://supabase.com/dashboard/project/ihivupqpctpkrgqgxfjf/auth/templates"
echo ""
echo "5. Test the app:"
echo "   - Signup: http://localhost:3000/signup"
echo "   - Login: http://localhost:3000/login"
echo "   - Dashboard: http://localhost:3000/dashboard"
echo ""
echo "The dev server is running at: http://localhost:3000"
echo ""
echo "Press Ctrl+C to stop the server when done testing."