name: Bug Report
description: File a bug report to help us improve LogYourBody
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      options:
        - Desktop
        - Mobile
        - Tablet

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
        - OS: [e.g. macOS 13.0, Windows 11, iOS 16]
        - Browser version: [e.g. Chrome 108.0.5359.124]
        - App version: [e.g. 1.0.0]
      placeholder: |
        OS: macOS 13.0
        Browser: Chrome 108.0.5359.124
        App version: 1.0.0
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. Include screenshots if applicable.
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true