name: 'Sync Certificates with Match'
description: 'Sync certificates and provisioning profiles using Fastlane match'
inputs:
  match_password:
    description: 'Passphrase for Fastlane match (MATCH_PASSWORD)'
    required: true
  match_git_url:
    description: 'Git URL for Fastlane match repository (MATCH_GIT_URL)'
    required: true
  match_git_basic:
    description: 'Basic auth credentials for git (username:password), embedded in URL'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Prepare MATCH_GIT_URL with credentials
      shell: bash
      run: |
        if [ -n "${{ inputs.match_git_basic }}" ]; then
          # Embed basic auth credentials into the git URL
          git_url_with_auth="${{ inputs.match_git_url/https:\/\//https:\/\/${{ inputs.match_git_basic }}@}}"
        else
          git_url_with_auth="${{ inputs.match_git_url }}"
        fi
        echo "MATCH_GIT_URL=$git_url_with_auth" >> $GITHUB_ENV
    - name: Setup Ruby and Bundler
      uses: ./.github/actions/setup-ruby-bundler
      with:
        working-directory: apps/ios
        cache-key-prefix: 'match-gems'
    - name: Sync certificates and provisioning profiles
      shell: bash
      run: |
        cd apps/ios
        bundle exec fastlane setup_provisioning
      env:
        MATCH_PASSWORD: ${{ inputs.match_password }}
        MATCH_KEYCHAIN_PASSWORD: ${{ inputs.match_password }}
