# SwiftLint configuration for LogYourBody iOS app
# Updated: July 14, 2025

# Paths to include/exclude
included:
  - LogYourBody
  - LogYourBodyWidget
  - LogYourBodyTests
  - LogYourBodyUITests

excluded:
  - Carthage
  - Pods
  - DerivedData
  - .build
  - build
  - LogYourBody/Models/LogYourBody.xcdatamodeld
  - "**/*.generated.swift"
  - "**/*.pb.swift"

# Disabled rules
disabled_rules:
  - todo # We use TODOs for tracking work
  - force_cast # Sometimes needed for Core Data
  - force_try # Used in some initialization code

# Enabled opt-in rules for better code quality
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 500
  error: 750

file_length:
  warning: 600
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]
  validates_start_with_lowercase: error

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

file_header:
  required_pattern: |
    \/\/
    \/\/  .*\.swift
    \/\/  LogYourBody.*
    \/\/

vertical_whitespace:
  max_empty_lines: 2

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

trailing_comma:
  mandatory_comma: false

# Custom rules
custom_rules:
  no_hardcoded_strings:
    name: "Hardcoded Strings"
    regex: '(Text|Label|Button|NavigationLink)\("[\w\s]{5,}"\)'
    message: "Consider using localized strings or constants for UI text"
    severity: warning
    match_kinds:
      - identifier

  mark_format:
    name: "MARK Format"
    regex: '// MARK: [^-]|// MARK:$'
    message: "Use format: // MARK: - Section Name"
    severity: warning

  no_print_statements:
    name: "Print Statements"
    regex: '\bprint\('
    message: "Remove print statements before committing"
    severity: warning
    match_kinds:
      - identifier

  space_after_comment:
    name: "Space After Comment"
    regex: '(\/\/\w+)|(\/\/  +)'
    message: "Use single space after //"
    severity: warning

  empty_count_check:
    name: "Empty Count"
    regex: '\.count\s*(==|!=|<|>|<=|>=)\s*0'
    message: "Use .isEmpty instead of checking .count"
    severity: error

  force_https:
    name: "Force HTTPS"
    regex: 'http://'
    message: "Use HTTPS instead of HTTP"
    severity: error
    match_kinds:
      - string


# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"