name: AI Issue Triage

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install anthropic PyGithub PyYAML

      - name: Analyze and triage issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python scripts/ai-issue-triage.py \
            --issue-number ${{ github.event.issue.number }} \
            --repo ${{ github.repository }}

      - name: Comment triage result
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // Read the triage result if it exists
            let triageResult = '';
            try {
              triageResult = fs.readFileSync('triage-result.json', 'utf8');
              const result = JSON.parse(triageResult);
              
              // Add labels based on triage
              if (result.labels && result.labels.length > 0) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: result.labels
                });
              }
              
              // Add comment with triage explanation
              if (result.comment) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: result.comment
                });
              }
            } catch (error) {
              console.log('No triage result found or error reading file:', error);
            }

      - name: Upload triage result
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: triage-result
          path: triage-result.json
          retention-days: 1