name: Enforce Branch Protection

on:
  workflow_dispatch:
  schedule:
    # Run daily to ensure branch protection rules are maintained
    - cron: '0 8 * * *'

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    permissions:
      administration: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y
    
    - name: Protect main branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api repos/${{ github.repository }}/branches/main/protection \
          --method PUT \
          --field required_status_checks='{"strict":true,"contexts":["test","lint"]}' \
          --field enforce_admins=true \
          --field required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true,"require_code_owner_reviews":false}' \
          --field restrictions='{"users":[],"teams":[],"apps":[]}' \
          --field allow_force_pushes=false \
          --field allow_deletions=false || echo "Main branch protection already exists or insufficient permissions"
    
    - name: Protect preview branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api repos/${{ github.repository }}/branches/preview/protection \
          --method PUT \
          --field required_status_checks='{"strict":true,"contexts":["test"]}' \
          --field enforce_admins=true \
          --field required_pull_request_reviews='{"required_approving_review_count":0,"dismiss_stale_reviews":false,"require_code_owner_reviews":false}' \
          --field restrictions='{"users":[],"teams":[],"apps":[]}' \
          --field allow_force_pushes=false \
          --field allow_deletions=false || echo "Preview branch protection already exists or insufficient permissions"