name: CI - Dev Branch

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  NODE_VERSION: '20'

jobs:
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm install
        
      - name: Run linting
        run: npm run lint
        
      - name: Run type checking
        run: npm run typecheck
        
      - name: Run tests
        run: npm test
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPA_DEV_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPA_DEV_ANON_KEY }}
          
      - name: Build Next.js application
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPA_DEV_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPA_DEV_ANON_KEY }}
          NEXT_PUBLIC_VERSION: ${{ github.sha }}
          
      - name: Run Supabase migrations (Dev)
        run: |
          npx supabase db push --project-ref ${{ secrets.SUPA_DEV_REF }} || true
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  create-pr-to-preview:
    name: Auto PR to Preview
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check for existing PR
        id: check-pr
        run: |
          PR_COUNT=$(gh pr list --base preview --head dev --state open --json number --jq '. | length')
          echo "count=$PR_COUNT" >> $GITHUB_OUTPUT
          
          if [ "$PR_COUNT" -gt 0 ]; then
            echo "Existing PR found from dev to preview"
            PR_NUMBER=$(gh pr list --base preview --head dev --state open --json number --jq '.[0].number')
            echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pull Request
        if: steps.check-pr.outputs.count == '0'
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          base: preview
          title: '🚀 Auto-merge: dev → preview'
          body: |
            ## Automated Pull Request
            
            This PR was automatically created after successful tests on the `dev` branch.
            
            ### ✅ All Checks Passed
            - Tests: ✅ Passed
            - Build: ✅ Successful
            - Type checking: ✅ Passed
            - Linting: ✅ Passed
            
            ### 📋 Changes
            View commit history for detailed changes.
            
            ### 🤖 Auto-merge
            This PR will be automatically merged if all checks continue to pass.
            
            ---
            *This is an automated pull request created by GitHub Actions.*
          labels: |
            automated
            dev-to-preview
            
      - name: Enable Auto-merge on New PR
        if: steps.check-pr.outputs.count == '0' && steps.cpr.outputs.pull-request-operation == 'created'
        run: |
          gh pr merge --auto --merge "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update Existing PR
        if: steps.check-pr.outputs.count != '0'
        run: |
          echo "PR #${{ steps.check-pr.outputs.number }} already exists from dev to preview"
          gh pr comment ${{ steps.check-pr.outputs.number }} --body "🔄 Updated with latest changes from dev branch"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}