name: CI - Preview Branch

on:
  push:
    branches: [preview]

env:
  NODE_VERSION: '20'

jobs:
  test-and-deploy:
    name: Test & Deploy Preview
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm install
        
      - name: Run linting
        run: npm run lint
        
      - name: Run type checking
        run: npm run typecheck
        
      - name: Run tests
        run: npm test
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPA_PRE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPA_PRE_ANON_KEY }}
          
      - name: Build Next.js application
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPA_PRE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPA_PRE_ANON_KEY }}
          NEXT_PUBLIC_VERSION: ${{ github.sha }}
          
      - name: Run Supabase migrations (Preview)
        run: |
          npx supabase db push --project-ref ${{ secrets.SUPA_PRE_REF }} || true
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          
      # Commented E2E tests - uncomment when ready
      # - name: Run Playwright E2E tests
      #   run: npm run playwright
      #   env:
      #     NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPA_PRE_URL }}
      #     NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPA_PRE_ANON_KEY }}
      #     PLAYWRIGHT_BASE_URL: https://preview-logyourbody.vercel.app
          
      - name: Notify deployment status
        run: |
          echo "✅ Preview environment tests passed"
          echo "🚀 Vercel will auto-deploy preview branch"
          echo "📱 Preview URL: https://preview-logyourbody.vercel.app"