name: iOS PR Verify

on:
  pull_request:
    branches: [dev]
    paths:
      - 'apps/ios/**'
      - '.github/workflows/ios-pr-verify.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rapid-checks:
    name: Rapid Checks
    runs-on: macos-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
    
    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: |
          apps/ios/vendor/bundle
          ~/Library/Developer/Xcode/DerivedData
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-ios-rapid-${{ hashFiles('**/Gemfile.lock', '**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-ios-rapid-
    
    - name: Install Dependencies
      run: |
        cd apps/ios
        gem install bundler:2.4.10
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        
        # Create placeholder config files
        echo "// CI Placeholder" > Supabase.xcconfig
        echo "SUPABASE_URL = https://placeholder.supabase.co" >> Supabase.xcconfig
        echo "SUPABASE_ANON_KEY = placeholder-key" >> Supabase.xcconfig
        
        echo "// CI Placeholder" > LogYourBody/Config.xcconfig
        echo "CLERK_PUBLISHABLE_KEY = placeholder-clerk-key" >> LogYourBody/Config.xcconfig
    
    - name: SwiftLint
      run: |
        cd apps/ios
        if ! command -v swiftlint &> /dev/null; then
          brew install swiftlint
        fi
        swiftlint lint --strict --reporter github-actions-logging
      continue-on-error: true
    
    - name: Build for Testing
      run: |
        cd apps/ios
        set -o pipefail
        
        xcodebuild -project LogYourBody.xcodeproj \
          -scheme LogYourBody \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -derivedDataPath build \
          clean build-for-testing \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          COMPILER_INDEX_STORE_ENABLE=NO \
          -quiet | xcbeautify --renderer github-actions
    
    - name: Run Unit Tests
      run: |
        cd apps/ios
        set -o pipefail
        
        xcodebuild -project LogYourBody.xcodeproj \
          -scheme LogYourBody \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -derivedDataPath build \
          test-without-building \
          -only-testing:LogYourBodyTests \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          COMPILER_INDEX_STORE_ENABLE=NO \
          -quiet | xcbeautify --renderer github-actions || true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ios-pr-test-results
        path: |
          apps/ios/build/Logs/Test/*.xcresult
        retention-days: 7