name: iOS CI

on:
  push:
    branches: [main, preview, dev]
    paths:
      - 'apps/ios/**'
      - '.github/workflows/ios-ci.yml'
  pull_request:
    branches: [main, preview, dev]
    paths:
      - 'apps/ios/**'
      - '.github/workflows/ios-ci.yml'

jobs:
  lint-and-test:
    runs-on: macos-latest
    timeout-minutes: 20
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
    
    # Improved caching with correct derived data path
    - name: Cache Swift Package Manager and Build
      uses: actions/cache@v4
      with:
        path: |
          apps/ios/build
          ~/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-spm-build-${{ hashFiles('**/Package.resolved', '**/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-spm-build-
    
    - name: Cache SwiftLint
      uses: actions/cache@v4
      id: swiftlint-cache
      with:
        path: /opt/homebrew/bin/swiftlint
        key: ${{ runner.os }}-swiftlint-0.55.1-homebrew
    
    - name: Cache Ruby gems
      uses: actions/cache@v4
      with:
        path: apps/ios/vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    
    - name: Install SwiftLint
      if: steps.swiftlint-cache.outputs.cache-hit != 'true'
      run: brew install swiftlint
    
    # Run lint in parallel with dependency setup
    - name: Setup Dependencies & Lint
      run: |
        cd apps/ios
        
        # Start Ruby setup in background
        (
          gem install bundler:2.4.10
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        ) &
        RUBY_PID=$!
        
        # Create config files
        echo "// CI Placeholder" > Supabase.xcconfig
        echo "SUPABASE_URL = https://placeholder.supabase.co" >> Supabase.xcconfig
        echo "SUPABASE_ANON_KEY = placeholder-key" >> Supabase.xcconfig
        
        echo "// CI Placeholder" > LogYourBody/Config.xcconfig
        echo "CLERK_PUBLISHABLE_KEY = placeholder-clerk-key" >> LogYourBody/Config.xcconfig
        
        # Run SwiftLint while Ruby installs
        if command -v swiftlint &> /dev/null; then
          swiftlint lint --strict --reporter github-actions-logging || true
        fi
        
        # Wait for Ruby setup
        wait $RUBY_PID
    
    # Build and test in one step
    - name: Build and Test
      run: |
        cd apps/ios
        
        # Use xcodebuild directly for better performance
        xcodebuild -project LogYourBody.xcodeproj \
          -scheme LogYourBody \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -derivedDataPath build \
          clean test \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          COMPILER_INDEX_STORE_ENABLE=NO \
          -quiet | xcbeautify
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ios-test-results
        path: |
          apps/ios/build/Logs/Test/*.xcresult
        retention-days: 7

  # Deploy to TestFlight from preview branch
  deploy-testflight:
    needs: lint-and-test
    if: github.ref == 'refs/heads/preview' && github.event_name == 'push'
    runs-on: macos-latest
    environment:
      name: preview
      url: https://testflight.apple.com
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1'
    
    - name: Cache Ruby gems
      uses: actions/cache@v4
      with:
        path: apps/ios/vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    
    - name: Install dependencies
      run: |
        cd apps/ios
        gem install bundler:2.4.10
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    
    - name: Import Code Signing Certificates
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
        p12-password: ${{ secrets.IOS_P12_PASSWORD }}
    
    - name: Download Provisioning Profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/distribution.mobileprovision
    
    - name: Setup App Store Connect API Key
      run: |
        cd apps/ios
        echo "${{ secrets.ASC_API_KEY_JSON }}" > app_store_connect_api_key.json
        echo "APP_STORE_CONNECT_API_KEY_PATH=$(pwd)/app_store_connect_api_key.json" >> $GITHUB_ENV
    
    - name: Build and Deploy to TestFlight
      run: |
        cd apps/ios
        bundle exec fastlane beta
      env:
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        APP_STORE_APP_ID: ${{ secrets.APP_STORE_APP_ID }}
        IOS_PROVISIONING_PROFILE_NAME: ${{ secrets.IOS_PROVISIONING_PROFILE_NAME }}
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: "180"
        FASTLANE_XCODEBUILD_SETTINGS_RETRIES: "10"
    
    - name: Cleanup API Key
      if: always()
      run: |
        cd apps/ios
        rm -f app_store_connect_api_key.json