name: iOS PR Verify

on:
  pull_request:
    branches: [dev]
    paths:
      - 'apps/ios/**'
      - '.github/workflows/ios-pr-verify.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rapid-checks:
    name: Rapid Checks
    runs-on: macos-14  # Use Apple Silicon for better performance
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup iOS build environment
      uses: ./.github/actions/setup-ios-build
      with:
        xcode-version: '16.1'
        setup-ruby: 'true'
        create-config-files: 'true'
    
    - name: Cache Swift packages and DerivedData
      uses: actions/cache@v4
      with:
        path: |
          apps/ios/.build
          ~/Library/Developer/Xcode/DerivedData
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-spm-xcode-16.1-${{ hashFiles('**/Package.resolved', '**/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-spm-xcode-16.1-
          ${{ runner.os }}-spm-
    
    - name: SwiftLint
      run: |
        cd apps/ios
        swiftlint lint --strict --reporter github-actions-logging
      continue-on-error: true
    
    - name: Build for Testing
      run: |
        cd apps/ios
        set -o pipefail
        
        xcodebuild -project LogYourBody.xcodeproj \
          -scheme LogYourBody \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -derivedDataPath build \
          clean build-for-testing \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          COMPILER_INDEX_STORE_ENABLE=NO \
          -quiet | xcbeautify --renderer github-actions
    
    - name: Run Unit Tests
      run: |
        cd apps/ios
        set -o pipefail
        
        xcodebuild -project LogYourBody.xcodeproj \
          -scheme LogYourBody \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -derivedDataPath build \
          test-without-building \
          -only-testing:LogYourBodyTests \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          COMPILER_INDEX_STORE_ENABLE=NO \
          -quiet | xcbeautify --renderer github-actions || true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ios-pr-test-results
        path: |
          apps/ios/build/Logs/Test/*.xcresult
        retention-days: 3